# Все CI/CD пайплайны начинаются с этого файла.
# GitLab Runner будет читать его и выполнять указанные инструкции.

# Определяем стадии. Задачи внутри одной стадии могут выполняться параллельно,
# а сами стадии выполняются последовательно.
stages:
  - test

# Описываем нашу первую задачу (job), которая будет проверять скрипт.
lint-bash-script:
  stage: test  # Эта задача принадлежит стадии 'test'.

  # Указываем, какой Docker-образ использовать для выполнения задачи.
  # Мы берем легковесный образ с Alpine Linux и устанавливаем в него shellcheck.
  image: alpine:latest

  # Скрипты, которые нужно выполнить перед основной задачей.
  before_script:
    - apk update && apk add shellcheck

  # Основной скрипт нашей задачи.
  script:
    - echo "Checking log_analyzer.sh for issues..."
    - shellcheck log_analyzer.sh